// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AdminSidebarController from "./admin_sidebar_controller"
application.register("admin-sidebar", AdminSidebarController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import VideoModalController from "./video_modal_controller"
application.register("video-modal", VideoModalController)
